name: chocolatine
on: 
  push:
    branches-ignore:
      - 'ga-ignore-'
  pull_request:
    branches-ignore:
      - 'ga-ignore-'

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-DOP-200-PAR-2-1-chocolatine-alfred.ternynck.git
  EXECUTABLES: a.out

jobs:
  action-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-death: 0
      - run: find -name .swp
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:Alfred-TERNYNCK/chocolatine.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}