
name: chocolatine
on: 
  push:
    branches-ignore:
      - 'ga-ignore-'
  pull_request:
    branches-ignore:
      - 'ga-ignore-'

env :
  MIRROR_URL: git@github.com:EpitechPromo2027/B-DOP-200-PAR-2-1-chocolatine-alfred.ternynck.git
  executable_name: ./a.out

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-death: 0
      - name: file.#
        run: |
          FILE2=$(find . -name *.#)
            if [[ -n "$FILE2" ]]; then
            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
            exit 1
            fi
      - name: file.~
        run: |
          FILE2=$(find . -name *.~)
            if [[ -n "$FILE2" ]]; then
            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
            exit 1
            fi
      - name: file.pain_choco
        run: |
          FILE2=$(find . -name "pain_au_chocolat")
            if [[ -n "$FILE2" ]]; then
            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
            exit 1
            fi
      - name: file.o
        run: |
          FILE2=$(find . -name *.o)
            if [[ -n "$FILE2" ]]; then
            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
            exit 1
            fi
      - name: file.a
        run: |
          FILE2=$(find . -name *.a)
            if [[ -n "$FILE2" ]]; then
            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
            exit 1
            fi
      - name: file.so
        run: |
          FILE2=$(find . -name *.so)
            if [[ -n "$FILE2" ]]; then
            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
            exit 1
            fi
      - name: file.gcno
        run: |
          FILE2=$(find . -name *.gcno)
            if [[ -n "$FILE2" ]]; then
            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
            exit 1
            fi
      - name: file.gcda
        run: |
          FILE2=$(find . -name *.gcda)
            if [[ -n "$FILE2" ]]; then
            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
            exit 1
            fi
      - name: file.gcov
        run: |
          FILE2=$(find . -name *.gcov)
            if [[ -n "$FILE2" ]]; then
            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
            exit 1
            fi
      - name: file.gch
        run: |
          FILE2=$(find . -name *.gch)
            if [[ -n "$FILE2" ]]; then
            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
            exit 1
            fi
      - name: file.gcovr
        run: |
          FILE2=$(find . -name *.gcovr)
            if [[ -n "$FILE2" ]]; then
            echo "::error file=$FILE2, line=1,col=5,endColumn=7::"
            exit 1
            fi
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:Alfred-TERNYNCK/chocolatine.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
