name: chocolatine
on: [push]
jobs:
  check_repository_cleanliness
  action-chekout:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        with:
          fetch-death: 0
        run: find -name .a